### ISSUE TITLE
Components checklist

### ISSUE THREAD

**Issue by Heydon** [bbc/gel#61]
- [ ] Remove/replace references to the `vh` (visually hidden) class
- [ ] Move older components to new constructor pattern
- [ ] "Expected" → "Recommended"
- [ ] "Example implementation" → "Reference implementation"
- [ ] Make sure there are no broken links (check for `#link-todo` placeholders)
- [ ] Make sure all asides/notes have a unique label ("Note" etc not good enough)
- [ ] Test reference implementations in Edge
- [ ] Normalize to singular form for filenames where appropriate (_gef-promo.scss, not _gef-promos.scss)
- [ ] Make all references to components bold and capitalized
- [ ] Make all constructor names uppercase (like `ShareTools`, not `shareTools`)
- [ ] Either remove the accessibility Boolean or set to true for all accepted components
- [ ] Comment JS code

**Comment by Heydon** [comment]
@micmath Add to this anything you think we need to look out for and I've missed ✊

**Comment by Heydon** [comment]
@micmath I get the "recommended" versus "expect" change, but I don't think "example implementation" is strong enough, because it's sort of saying "here's one way but do what you like". "Reference implementation" is better because it doesn't exactly _mandate_ anything (there's the disclaimer anyway) but it does say "you should learn from this".

**Comment by Heydon** [comment]
## Tally

### Card ✅

Outstanding:

* Remaining #linktocome, referencing a wiki page

**Comment by micmath** [comment]
How far along are we on the list, @Heydon ?

**Comment by Heydon** [comment]
@micmath I've done all the Edge (and IE11) testing except for for the routing one. I think we're good, but it would be fantastic if you did these and your own checks too, and requested any changes needed.

**Comment by micmath** [comment]
agreed.
